### ISSUE TITLE
Set up local environments

### ISSUE THREAD

**Issue by kdholland** [RadishLab/TAT001#1]
Hi guys! Please set up your local environments for this project.

Let me know if you need anything.

**Comment by ChrisBup** [comment]
@kdholland Just an update. I began this on Friday but am still setting things up. Should be able to get it completed this morning, barring any snags.

**Comment by andyinabox** [comment]
I'm good to go on this one! 👌 

![screen shot 2017-12-04 at 12 49 05 pm](https://user-images.githubusercontent.com/151084/33570159-90144d3c-d8f1-11e7-8220-c675fdaf26c7.png)

**Comment by kdholland** [comment]
@ChrisBup are you all set up?
