### ISSUE TITLE
Country Fact Pages - Backend

### ISSUE THREAD

**Issue by kdholland** [RadishLab/TAT001#12]
Design TBD

There will be a page for every country in the backend, and another place in the background where the master CSV where all of the country data lives.

Example of their master country data (final to come): https://www.dropbox.com/s/atdb8u58vesconh/TA6_factsheet_notfinal.xlsx?dl=0

The fact pages will pull data from their master spreadsheet that has all of the statistics on it. They only want to update this info via CSV upload so it doesn't need to be editable in the CMS, but it would be nice if the fields still were there but grayed out. Not totally necessary though.

We can talk more about this as we get the design finalized, but they are great with formatting data so if you need it to be formatted or presented differently, let me know.

**Comment by kdholland** [comment]
Let me know if you have enough to get started here - Ed made some outlines here of what it will look like on the frontend: https://invis.io/FMF0N8Y5Y#/269931687_Fact_Sheet_-_Issues

**Comment by andyinabox** [comment]
Yes that should be plenty for me to get started! I assume the boxes are charts that Eric will be developing?

**Comment by andyinabox** [comment]
@kdholland do we have an example of the master spreadsheet? this would be helpful when designing the backend

**Comment by andyinabox** [comment]
oops, sorry disregard ... i see you linked above :)

**Comment by andyinabox** [comment]
From the Dev Doc:
> * Data comes from master CSV - in single place (Universal theme options)
>   * Data can be updated by CSV upload only
>   * Fields for data points can be in fact page CMS but should be grayed out if they appear

**Comment by andyinabox** [comment]
@kdholland one question related to this. Do you think it would be acceptable behavior to use the CSV to generate the country pages

**Comment by kdholland** [comment]
@andyinabox I'm not sure what you mean - could you explain a bit more what you mean?

**Comment by andyinabox** [comment]
@kdholland sorry about that—

So I'm thinking it might work well to have the Country posts generated from the CSV file when it's imported, rather than add them via the WP interface. Then when the data is updated, it will just edit the pages if they already exist. The posts could still remain editable for tagging, etc if needed, but it would probably be cleanest if we disabled manually adding pages via the WordPress CMS (so that they're only added via CSV upload). 

Does that make sense to you?

**Comment by kdholland** [comment]
@andyinabox that's interesting... I think it would be great if it could be this clean, but I'm not 100% sure if it would work. ccing @edwerd here in case he has any thoughts and since he's working on the designs for this.

**Comment by edwerd** [comment]
@andyinabox That sounds like the right way to be thinking about this. Can you please reach out to @jaymullen to discuss our approach to the Hewlett grants import. We use a similar method to update data there.

**Comment by andyinabox** [comment]
@edwerd sure thing, thanks

**Comment by andyinabox** [comment]
@kdholland one other question -- I'm guessing this will have some sort of charts for each country, which will be developed by Eric. Correct? If so I'll sync up with him as well...

**Comment by kdholland** [comment]
@andyinabox Possibly, but not definitely... this is all still a little TBD. I know we're planning to include illustrations this year but I'm not sure about data visualizations.

**Comment by edwerd** [comment]
@andyinabox As of right now, these pages are still being planning out. Will follow up once our plan is cemented.

**Comment by andyinabox** [comment]
@kdholland @edwerd ok thanks. After today I'll have the CSV import pretty much set up, and then we can hash out the details. Although there's one other question that could change things significantly for the implementation:

Currently, the example CSV file has numerical data as well as written text data. Are we planning to also add translation capability to the data imported from CSV? It's not impossible, but would make things more complicated.

**Comment by kdholland** [comment]
@andyinabox Could you clarify what you mean? What is it that would complicate things? My sense is that we should require them to upload separate CSVs for each language.

**Comment by andyinabox** [comment]
@kdholland ah yes, separate CSV files makes sense. I was thinking in terms of translating the text strings via WPML after the CSV upload, but that's much more complicated.

**Comment by kdholland** [comment]
That sounds right to me but we should really be running this by Eric as well. I invited him to this repo so I'll loop him in once he accepts!

**Comment by andyinabox** [comment]
- [x] Get CSV loading to work
- [x] Automatically generate posts from CSV
- [x] Display fields in post edit
- [x] Show CSV data on page 
- [ ] CSV uploading for multiple languages
- [ ] Test rendering different languages from CSV

**Comment by andyinabox** [comment]
Seems like I should wait on the last part until I know more about how we'll be handling the different languages in CSV...

**Comment by kdholland** [comment]
Kamino cloned this issue to RadishLab/TAT001
