### ISSUE TITLE
Design News Page + Components

### ISSUE THREAD

**Issue by edwerd** [RadishLab/TAT001#33]
Hey @ChrisBup 
We're going need you to jump in and design a few pages on this site before working on development this week. 

I've saved a version of the designs for you to work on here: 
https://www.dropbox.com/s/ck0cr8cwqkauccw/TAT001%20-%20Creative%20Direction%20v3.sketch?dl=0

Wireframes for the News Index, News Single and Search index can be found here:
https://projects.invisionapp.com/d/main#/console/12317013/260317310/preview 
(News is called Blog in the wireframes)

Items we need to design:
- News / Search Index
- News Single 
- Each component from the development document: https://docs.google.com/document/d/15wvYB7-bfOTSTU_UGpDoMOa-Qr6vGbbIr1XmimoGdHA/edit#

**Comment by kdholland** [comment]
Kamino cloned this issue to RadishLab/TAT001
