### ISSUE TITLE
Build Post Types Framework 

### ISSUE THREAD

**Issue by kdholland** [RadishLab/TAT001#6]
Build the framework for the post types we'll use for this project

Outlined in dev doc: https://docs.google.com/document/d/15wvYB7-bfOTSTU_UGpDoMOa-Qr6vGbbIr1XmimoGdHA/edit#

Let me know if you have any questions!

**Comment by andyinabox** [comment]
Wiki page: https://github.com/RadishLab/TAT001/wiki/Custom-Post-Types

**Comment by andyinabox** [comment]
@kdholland one question related to this -- for taxonomies the dev doc lists:

> - Topics (Pulled from Post Type)
> - Countries (Pulled from Post Type)

What does "Pulled from Post Type" mean?

**Comment by andyinabox** [comment]
Took care of this in #31

**Comment by andyinabox** [comment]
![tat001 sitemap v2](https://user-images.githubusercontent.com/151084/33853022-186e3a7c-de82-11e7-9bba-41706324cca9.png)

**Comment by kdholland** [comment]
Kamino cloned this issue to RadishLab/TAT001
