### ISSUE TITLE
Pagebuilder

### ISSUE THREAD

**Issue by kdholland** [RadishLab/TAT001#7]
Build out the Pagebuilder to be used on the Topic and News pages 

Pagebuilder Components: 

- [x] WYSIWYG 
- [x] Data Visualization (graph/chart)
- [x] Photo/Illustration
- [x] Map (full-width)
- [x] Related Content
- [x] References
- [x] Text Callout
- [x] Good/Bad/Cutting Edge
 
**Notes**
* Look at the CultureTrack site for reference. Ed is giving you access now.
* Please take language translation into consideration when building this - each component will be translated into five languages, so we need to do this in a way so that it remainsusable

**Comment by andyinabox** [comment]
Pagebuilder usage notes from Jay:

the basic gist of it is that you create a new acf field group and you set the post type to 'Layout'

<img width="899" alt="screen shot 2017-12-01 at 12 15 31 pm" src="https://user-images.githubusercontent.com/151084/33630578-7e46b5e0-d9cd-11e7-90c8-86a69146b50b.png">

That automatically registers it as a "component" in the page builder which you can see on this page: http://tat001.alloy.radish.nyc/wp-admin/post.php?post=2&action=edit

<img width="697" alt="screen shot 2017-12-01 at 12 17 06 pm" src="https://user-images.githubusercontent.com/151084/33630608-99af5f26-d9cd-11e7-99c5-4a0ab86ab439.png">

then all you have to do is build the component out on the front end however you want

<img width="824" alt="screen shot 2017-12-01 at 12 17 42 pm" src="https://user-images.githubusercontent.com/151084/33630647-beb0cdd2-d9cd-11e7-958d-9d6dd64fee4e.png">

just register new components at the top of `views/page-builder/_layout_builder.php` and that mumble jumble of code below should load the template file (as long as you have created it)

**Comment by kdholland** [comment]
@andyinabox Yep - key word is somewhat. I made the initial list and Jay went through the designs and added other components he saw, but the designs are still being finalized so it's subject to change.

**Comment by andyinabox** [comment]
Wiki page: https://github.com/RadishLab/TAT001/wiki/Pagebuilder

**Comment by andyinabox** [comment]
Going to try and use the Data Visualization component for maps until I find a reason not to...

**Comment by andyinabox** [comment]
Got the basic framework in as much as I could without more details on the component framework. I'll post a link to sample page once I get my deploy working (something isn't going right with deploy to staging)

**Comment by andyinabox** [comment]
FYI -- I fixed the deploy so now you can see the example page here:

http://tat001.alloy.radish.nyc/our-arrival/

(No styles so doesn't look like much yet)
