### ISSUE TITLE
Language Translation

### ISSUE THREAD

**Issue by kdholland** [RadishLab/TAT001#9]
The website will be translated into:

* Chinese
* Spanish
* French
* Arabic
* Portuguese

Ed was thinking we could use the same plugin used for this site: https://corenav.org/

Need to figure out how this is going to work with the Pagebuilder

**Comment by andyinabox** [comment]
Notes on alternative plugins here: https://github.com/RadishLab/TAT001/wiki/Localization-and-Translation

WPML seems to be a favorite but there are others worth considering.

**Comment by andyinabox** [comment]
@kdholland I have a few follow-up questions for this one:

1. What is the preference toward machine-translated, crowdsourced, or professional translation?
1. Do we need the plugin to have a lot of features for managing doing the actual translation, or will the client be doing that through other means?
1. How do we want to handle the urls? Examples:
	- Subdomain: `http://en.tobaccoatlas.org/`
	- Query var: `http://www.tobaccoatlas.org/?lang=en`
	- Path: `http://www.tobaccoatlas.org/en/`
	- Separate domain for each language(this is what is currently in use)

**Comment by kdholland** [comment]
@andyinabox I'm going to check with the client. I'll add you on the Basecamp post.

For the URLs, before I ask if they have a preference, a few questions:
- Is any option a much heavier lift than the others? 
- Is any option better for SEO?
- Do any of plugins you've researched require that any particular method be used?

**Comment by andyinabox** [comment]
> Is any option a much heavier lift than the others?

For WPML and other plugins I'm looking at it seems like they're all about the same. There will be bit of extra DNS configuration for different subdomains or domains, but not too bad.

> Is any option better for SEO?

It looks like as far as SEO is concerned, I'm seeing that the best options are:

1. Using a country-specific TLD like `http://www.tobaccoatlas.fr`
2. Using a subdomain (`http://fr.tobaccoatlas.org`)
3. Using a path (`http://www.tobaccoatlas.org/en/`)

But [according to Google](https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/webmasters/klzxSTpqWbc/6IiP4XrYFAAJ) there's no difference between 2 and 3 as far as rankings are concerned.

**Comment by kdholland** [comment]
@andyinabox sorry - one more question I thought of:

Each topic page URL is going to have a short URL as well, e.g. www.tobaccoatlas.com/growing will also need to be accessible by www.ta6.org/growing

Does this introduce any complications language-wise or will the ta6.org domain just be redirecting to the tobaccoatlas.com one, which will have the subdomain or path?

**Comment by andyinabox** [comment]
I don't think so ... going to the short link should just redirect to the normal one, and then whatever behavior we have there (say we want to redirect based on language) will still kick in.

**Comment by andyinabox** [comment]
Also, it might make sense to do multiple short links that are language-based. For instance:

```
www.ta6.org/growing   -> en.tobaccoatlas.com/growing
www.ta6.org/creciente -> en.tobaccoatlas.com/growing
```
Or something like that?

**Comment by andyinabox** [comment]
@kdholland one other thing I just thought of ... will they need these translations on the background/admin as well? Or can that remain just in English?

**Comment by kdholland** [comment]
@andyinabox re: the language-based short links, that's an awesome idea. I'll run it by them.

Yes - they just got back to me and all translations will be manual. They're not happy with the machine translations so they will be entering in all of the translations themselves in the CMS for every piece of content. This is why we're concerned about the pagebuilder being unwieldy and choosing the right plugin - five separate fields for each component could become hard to use!

**Comment by kdholland** [comment]
@andyinabox Another question came up - if we add a language to the site and a user tries to load a page in that language but the content isn't filled out yet, will it default to English or show a message like "Translation coming soon."? 

Also, is it possible to have a language disabled from the frontend while the client adds translations to the CMS and then enable it when they're done? This is another option I may present to them if it's possible.

**Comment by andyinabox** [comment]
@kdholland 

> They're not happy with the machine translations so they will be entering in all of the translations themselves in the CMS for every piece of content.

Great, that makes sense. There are also some plugins that can integrate (paid) services for crowd-sourced or professional translations into the WP interface, but if they already have a translation service they're using it might not be all that necessary.

Also, it's probably better if we avoid taking on WP-integrated translation unless they specifically ask for it, seems like it could add more headaches.

> This is why we're concerned about the pagebuilder being unwieldy and choosing the right plugin - five separate fields for each component could become hard to use!

Yes, I'm going to finish evaluating plugins today and ACF support (which Pagebuilder is built on) is high on my list.

> Another question came up - if we add a language to the site and a user tries to load a page in that language but the content isn't filled out yet, will it default to English or show a message like "Translation coming soon."?
>
> Also, is it possible to have a language disabled from the frontend while the client adds translations to the CMS and then enable it when they're done? This is another option I may present to them if it's possible.

I'm pretty sure these are possible, but not sure how much effort they would take (my guess is not too much). I'll try and get a better sense when I finish researching multi-language plugin options today.

**Comment by kdholland** [comment]
@andyinabox Cool, thanks for looking into this. I agree about doing any WP-integrated translations. The client has been pretty clear that they want complete control over them. 

cc'ing @ChrisBup in case he has any thoughts on any of this, otherwise I'll wait to hear back from you about your plugin recommendation.

**Comment by andyinabox** [comment]
Ok, it looks like [WPML Multilingual CMS](https://wpml.org/purchase/) is the best option, which the client will have to pay for.

Unfortunately from what I could find there are no great options for ACF Flexible Content Fields (which Pagebuilder depends on) Getting WPML to work with well Pagebuilder will definately take some extra development, but it does have well-documented ACF support and there are a few breadcrumbs on the forums to help with this. 

Once we get the license and everything I can start digging into how to get it working with Pagebuilder. Out of the box it should technically work, it will just be really unwieldy without some extra help.

Other things that WPML supports relevant to this project:

* Editing RTL text correctly in the admin
* Disable language until translation is done
* Subdomain-based language sites (`fr.tobaccoatlas.org`)
* Supported by ACF (WPML is the only multi-language option they mention on their site)

I'm not sure about the "translation coming soon" option but it seems like that might be something we could handle in the template.

I also [took a bunch of notes on the wiki](https://github.com/RadishLab/TAT001/wiki/Localization-and-Translation).

**Comment by kdholland** [comment]
@andyinabox Awesome. Thank you.

@edwerd Do we have a bulk WPML license by any chance or do we need to ask the client to purchase a license for the project?

**Comment by edwerd** [comment]
@chris can you please share our licence keep with @kdholland @andyinabox

**Comment by ChrisBup** [comment]
@andyinabox  @kdholland @edwerd I added http://tat001.alloy.radish.nyc to our WPML account: https://wpml.org/account/ (login in 1Password) which provides a key for us to use. @andyinabox Let me know if you don't have access to 1P and I'll just send you the WPML login.

**Comment by andyinabox** [comment]
@ChrisBup no I'm not on the 1P, maybe just send me the WPML login? Thanks!

**Comment by andyinabox** [comment]
@kdholland a few more questions related to this:

**Do we want to use "Simplified" or "Traditional" Chinese?** Seems like the distinction is [a bit complicated](https://www.simultrans.com/blog/chinese-localization), but the short version is:

> Simplified Chinese is based on traditional, but has fewer character strokes. Simplified Chinese today is used in China and Singapore, whereas Traditional Chinese is used in Hong Kong and in Taiwan.

My guess is we want "simplified" so I'll go with that unless I hear otherwise.

**Do we want to target Brazilian Portuguese or Portuguese Portuguese?** I'm guessing Brazilian so I'll stick with that until I hear otherwise.

**Comment by kdholland** [comment]
@andyinabox Posted to the client about this!

**Comment by kdholland** [comment]
@andyinabox **Traditional Chinese** and **Brazilian Portuguese**
